jade_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('matricula.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

matricula/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from .tokens import user_tokenizer


urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.logar, name='login'),
    path('registrar_usuario/', views.registrar_usuario, name='registrar_usuario'),
    path('registrar_aluno/', views.registrar_aluno, name='registrar_aluno'),
    path('logout/', views.deslogar, name='logout'),
    path('solicitar_matricula/', views.matricular, name="solicitar_matricula"),
    path('consultar_matricula/', views.consultar_matricula, name="consultar_matricula"),
    path('excluir_matricula', views.excluir_matricula, name="excluir_matricula"),
    path('detalhe_matricula', views.detalhe_matricula, name="detalhe_matricula"),
    path('sistema/matriculas', views.processar_matriculas, name="processar_matriculas"),
    path('sistema/matriculas/editar/<int:id_matricula>', views.editar_matricula, name='editar_matricula'),
    path('sistema/atualizar_bd', views.atualizar_bd, name="atualizar_bd"),
    path('sistema/relatorios/departamentos', views.report_departamentos, name='relatorio_departamentos'),
    path('sistema/relatorios/disciplinas', views.report_disciplinas, name='relatorio_disciplinas'),
    path('sistema/relatorios/turmas', views.report_turmas, name='relatorio_turmas'),
    path('sistema/relatorios/alunos', views.report_alunos, name='relatorio_alunos'),
    path('sistema/relatorios/alunos_fora', views.report_alunos_fora, name='relatorio_alunos_fora'),
    path('sistema/resetar_senha', auth_views.PasswordResetView.as_view(
        template_name="sistema/reset_password.html",
        html_email_template_name='sistema/reset_password_email.html',
        subject_template_name='sistema/subject_reset_password.txt',
        success_url=settings.LOGIN_URL,
        token_generator=user_tokenizer,
    ), name="reset_password"),
    path('reset-password-confirmation/<str:uidb64>/<str:token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='sistema/reset_password_update.html', 
        post_reset_login=True,
        post_reset_login_backend='django.contrib.auth.backends.ModelBackend',
        token_generator=user_tokenizer,
        success_url=settings.LOGIN_REDIRECT_URL
    ),name='password_reset_confirm'),
    path('calendario', views.show_calendario, name="calendario"),
    path('ajax/load_turmas', views.load_turmas, name="load_turmas"),
    path('ajax/load_cursos', views.load_cursos, name="load_cursos"),
    path('ajax/load_disciplinas', views.load_disciplinas, name="load_disciplinas"),
    path('ajax/load_tipo_matricula', views.load_tipo_matricula, name="load_tipo_matricula"),
    path('ajax/load_categoria_aluno', views.load_categoria_aluno, name="load_categoria_aluno"),
    path('ajax/load_status_matricula', views.load_status_matricula, name="load_status_matricula"),
    path('ajax/load_semesters', views.load_semesters, name="load_semesters"),
    path('ajax/load_editar_matricula/<int:id_matricula>', views.load_editar_matricula, name="load_editar_matricula"),
    path('ajax/delete_matricula/<int:id_matricula>', views.delete_matricula_ajax, name="delete_matricula_ajax"),
    path('ajax/update_atendida/<int:id_matricula>/<int:value>', views.update_atendida_ajax, name="update_atendida"),
    path('ajax/batch_update', views.batch_update, name="batch_update"),
    path('download/<path:file_name>', views.download_file, name="download_file"),
    path('teste', views.teste_upload, name='teste_upload'),
]

matricula/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from .db_update import update_db, handle_turma, handle_aluno
import pandas as pd
from django.shortcuts import get_object_or_404




class Administrador(models.Model):
    nome = models.CharField("Nome", max_length=255)
    categoria = models.CharField("Categoria", max_length=20)
    user = models.OneToOneField(User, related_name="admin", on_delete=models.CASCADE)

    def __str__(self):
        return self.nome



class Aluno(models.Model):

    def get_rg_path(self, filename):
        cs = Calendario().get_current_semester()
        ext = filename.split('.')[-1]
        arquivo = "{0}/{1}/RG-{2}.{3}".format(cs.ano, cs.semestre, self.user_id, ext)
        return arquivo

    def get_comp_path(self, filename):
        cs = Calendario().get_current_semester()
        ext = filename.split('.')[-1]
        arquivo = "{0}/{1}/COMP-{2}.{3}".format(cs.ano, cs.semestre, self.user_id, ext)
        return arquivo

    nome = models.CharField("Nome", max_length=255, blank=True, null=True)
    ra = models.CharField("R.A.", max_length=20, blank=True, null=True)
    rg = models.CharField("R.G.", max_length=20, blank=True, null=True)
    cpf = models.CharField("CPF", max_length=11)
    telefone = models.CharField("Telefone", max_length=20, null=True, blank=True)
    email = models.CharField("Email", max_length=255, null=True, blank=True)
    universidade = models.CharField("Universidade", max_length=255, blank=True, null=True)
    curso = models.CharField("Curso", max_length=255, blank=True, null=True)
    cr = models.DecimalField("Coeficiente de Rendimento", max_digits=5, decimal_places=4, blank=True, null=True)
    cm = models.DecimalField("Coeficiente de Matrícula", max_digits=5, decimal_places=4, blank=True, null=True)
    cp = models.DecimalField("Coeficiente de Progressão", max_digits=5, decimal_places=4, blank=True, null=True)
    mp = models.DecimalField("Média Ponderada", max_digits=5, decimal_places=4, blank=True, null=True)
    categoria = models.ForeignKey("Categoria_Aluno", models.PROTECT, 'alunos_categoria', default=1, blank=True, null=True)
    rg_file = models.FileField("Arquivo RG", upload_to=get_rg_path, blank=True, null=True)
    comprovante_file = models.FileField("Arquivo Comprovante", upload_to=get_comp_path, blank=True, null=True)
    file_upload_date = models.DateTimeField("Data do upload dos arquivos", blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="aluno", null=True, blank=True)

    def __str__(self):
        if self.nome is None:
            return self.cpf
        return self.nome

    def get_aluno_cpf(self, cpf):
        try:
            aluno = get_object_or_404(self.__class__, cpf=cpf)
        except:
            aluno = None
        return aluno

    def matricular(self, turma, tipo, justificativa, rg_file, comprovante_file):
        data_solicitacao = datetime.datetime.now()
        s = Status_matricula()
        status = s.get_status("Em análise")
        atendida = False
        id_cancelada = Status_matricula().get_id_cancelada()
        if Matricula.objects.filter(turma=turma, aluno=self).exclude(status_id=id_cancelada):
            nova_matricula = 1  # já matriculado
        else:
            nova_matricula = Matricula(turma=turma, aluno=self, tipo_id=tipo, data_solicitacao=data_solicitacao.date(),
                                   justificativa=justificativa, status=status, atendida=atendida)
            nova_matricula.save()
            if rg_file != "" and comprovante_file != "":
                self.rg_file = rg_file
                self.comprovante_file = comprovante_file
                self.file_upload_date = data_solicitacao
                self.save()
        return nova_matricula

    def create_student(self, fields_student):
        student = Aluno.objects.create(**fields_student)
        return student

    def get_all_alunos(self):
        return Aluno.objects.all()

    def get_alunos_fora(self):
        return Aluno.objects.exclude(universidade="FCAV")

    def update_model(self, file, tipo):
        handle_aluno(self, file, tipo)
        # if tipo != "delete_all":
        #     handle_aluno(self, file, tipo)
        # else:
        #     update_db(self, file, tipo)
        # return
        


class Categoria_Aluno(models.Model):
    categoria = models.CharField("Categoria", max_length=255)

    def __str__(self):
        return self.categoria

    def get_categorias(self):
        return Categoria_Aluno.objects.all()



class Curso(models.Model):
    codigo = models.CharField("Código", max_length=10, primary_key=True)
    nome = models.CharField("Nome do Curso", max_length=255)
    universidade = models.ForeignKey("Universidade", models.PROTECT, related_name="cursos")

    def __str__(self):
        return self.nome + " (" + self.universidade.nome + ")"

    def get_todos_cursos_fcav(self):
        cursos = Curso.objects.filter(universidade=Universidade.objects.get(nome="FCAV"))
        return cursos

    def get_curso_fcav(self, codigo_fcav):
        cursos = Curso.objects.get(universidade=Universidade.objects.get(nome="FCAV"), codigo=codigo_fcav)
        return cursos



class Universidade(models.Model):
    choices_estado = [
        ('SP', 'São Paulo'),
        ('RJ', 'Rio de Janeiro'),
        ('MG', 'Minas Gerais'),
    ]
    nome = models.CharField("Nome", max_length=255)
    cidade = models.CharField("Cidade", max_length=255)
    estado = models.CharField("Estado", choices=choices_estado, max_length=2, default="SP")

    def __str__(self):
        return self.nome + " - " + self.cidade + "/" + self.estado



class Departamento(models.Model):
    codigo = models.CharField("Código", max_length=10, primary_key=True)
    nome = models.CharField("Nome do Departamento", max_length=255)

    def __str__(self):
        return self.nome


    def update_model(self, file, tipo):
        update_db(self, file, tipo)
        return


    def get_all_departamentos(self):
        return Departamento.objects.all()


class Departamento_teste(models.Model):
    codigo = models.CharField("Código", max_length=10, primary_key=True)
    nome = models.CharField("Nome do Departamento", max_length=255)

    def __str__(self):
        return self.nome

    def update_model(self, file, tipo):
        update_db(self, file, tipo)
        return



class Disciplina(models.Model):
    codigo = models.CharField("Código", max_length=20, primary_key=True)
    nome = models.CharField("Nome da Disciplina", max_length=255)
    carga_horaria = models.PositiveSmallIntegerField("Carga Horária (horas)")
    departamento = models.ForeignKey("Departamento", models.PROTECT, related_name="disciplinas")

    def __str__(self):
        return self.codigo + " - " + self.nome

    def update_model(self, file, tipo):
        update_db(self, file, tipo)
        return

    def get_disciplinas_depto(self, depto):
        return Disciplina.objects.filter(departamento__codigo__icontains=depto)



class Calendario(models.Model):
    semestre = models.PositiveSmallIntegerField("Semestre")
    ano = models.PositiveIntegerField("Ano")
    inicio_semestre = models.DateTimeField("Início do Semestre", null=True)
    fim_semestre = models.DateTimeField("Término do Semestre", null=True)
    inicio_ae = models.DateTimeField("Início Aluno Especial", null=True)
    fim_ae = models.DateTimeField("Término Aluno Especial", null=True)
    inicio_aj = models.DateTimeField("Início Ajustes", null=True)
    fim_aj = models.DateTimeField("Término Ajustes", null=True)
    inicio_eq = models.DateTimeField("Início Equivalentes", null=True)
    fim_eq = models.DateTimeField("Término Equivalentes", null=True)

    def __str__(self):
        return str(self.semestre) + "º semestre de " + str(self.ano)

    def get_all_semestres(self):
        return Calendario.objects.all()

    def get_current_semester(self):
        now = datetime.datetime.now()
        try: 
            current_semester = get_object_or_404(Calendario, inicio_semestre__lte=now, fim_semestre__gte=now)
        except:
            current_semester = Calendario.objects.order_by('-ano', '-semestre')[0]
        return current_semester

    def is_active_ae(self):
        now = datetime.datetime.now()
        active_ae = Calendario.objects.filter(inicio_ae__lte=now, fim_ae__gte=now)
        return active_ae.exists()

    def is_active_aj(self):
        now = datetime.datetime.now()
        active_aj = Calendario.objects.filter(inicio_aj__lte=now, fim_aj__gte=now)
        return active_aj.exists()

    def is_active_eq(self):
        now = datetime.datetime.now()
        active_eq = Calendario.objects.filter(inicio_eq__lte=now, fim_eq__gte=now)
        return active_eq.exists()



class Turma(models.Model):
    choices_tipo = [
        ('TP', 'Teórico-prática'),
        ('T', 'Teórica'),
        ('P', 'Prática'),
    ]
    turma = models.CharField("Turma", max_length=10)
    calendario = models.ForeignKey("Calendario", models.PROTECT, related_name="turmas_semestre")
    disciplina = models.ForeignKey("Disciplina", models.PROTECT, related_name="turmas_disciplina")
    curso = models.ForeignKey("Curso", models.PROTECT, related_name="turmas_curso")
    tipo = models.CharField("Tipo", choices=choices_tipo, max_length=2, default="TP")
    #turma_teorica VER COMO IMPLEMENTA RELACIONAMENTO COM ELA MESMA, SOMENTE PARA TURMAS DO TIPO T

    def __str__(self):
        return self.disciplina.codigo + self.turma + " - " + self.disciplina.nome

    def get_turmas_curso(self, curso): #filtrar por curso após teste
        turmas = Turma.objects.filter(curso=curso)
        return turmas

    def get_turmas_disciplina(self, disciplina):
        turmas = Turma.objects.filter(disciplina=disciplina).order_by("turma")
        return turmas

    def get_turmas_depto(self, depto):

matricula/templates/relatorios/alunos.html
{% extends 'matricula/index.html' %}

{% block content %}
    <div class="container-fluid">
        <table class="table table-striped table-hover table-sm small">
            <thead class="thead-unesp">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">RA</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Email</th>
                    <th scope="col">Universidade</th>
                    <th scope="col">Curso</th>
                    <th scope="col">User</th>
                </tr>
            </thead>
            {% for aluno in alunos %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ aluno.ra }}</td>
                    <td>{{ aluno.nome }}</td>
                    <td>{{ aluno.telefone }}</td>
                    <td>{{ aluno.email }}</td>
                    <td>{{ aluno.universidade }}</td>
                    <td>{{ aluno.curso }}</td>
                    <td>{{ aluno.user.username }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

matricula/templates/relatorios/alunos_fora.html
{% extends 'matricula/index.html' %}
{% load filtros_matricula %}

{% block content %}
    <div class="container-fluid">
        {% for message in messages %}
            <div class="alert alert-danger alert-sm">{{ message }}</div>
        {% endfor %}
        <table class="table table-striped table-hover table-sm small">
            <thead class="thead-unesp">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Email</th>
                    <th scope="col">Universidade</th>
                    <th scope="col">Curso</th>
                    <th scope="col">RG</th>
                    <th scope="col">Comprovante</th>
                    <th scope="col">Último upload</th>
                </tr>
            </thead>
            {% for aluno in alunos %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ aluno.nome|c_bool_none:"Sim,Não," }}</td>
                    <td>{{ aluno.telefone|c_bool_none:"Sim,Não," }}</td>
                    <td>{{ aluno.email|c_bool_none:"Sim,Não," }}</td>
                    <td>{{ aluno.universidade|c_bool_none:"Sim,Não," }}</td>
                    <td>{{ aluno.curso|c_bool_none:"Sim,Não," }}</td>
                    <td>
                        {% if aluno.rg_file %}
                            <a href="{% url 'download_file' aluno.rg_file %}" download>Download</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if aluno.comprovante_file %}
                            <a href="{% url 'download_file' aluno.comprovante_file %}" download>Download</a>
                        {% endif %}
                    </td>
                    <td>{{ aluno.file_upload_date|c_bool_none:"Sim,Não," }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

matricula/templates/relatorios/departamentos.html
{% extends 'matricula/index.html' %}

{% block content %}
    <div class="container-fluid">
        <table class="table table-striped table-hover table-sm small">
            <thead class="thead-unesp">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Código</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Nº de disciplinas</th>
                </tr>
            </thead>
            {% for departamento in departamentos %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ departamento.codigo }}</td>
                    <td>{{ departamento.nome }}</td>
                    <td>{{ departamento.disciplinas.count }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

matricula/templates/relatorios/disciplinas.html
{% extends 'matricula/index.html' %}

{% block content %}
    <div class="container-fluid">
        <table class="table table-striped table-hover table-sm small">
            <thead class="thead-unesp">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Código</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Carga Horária (h)</th>
                    <th scope="col">Departamento</th>
                </tr>
            </thead>
            {% for disciplina in disciplinas %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ disciplina.codigo }}</td>
                    <td>{{ disciplina.nome }}</td>
                    <td>{{ disciplina.carga_horaria }}</td>
                    <td>{{ disciplina.departamento }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

matricula/templates/relatorios/turmas.html
{% extends 'matricula/index.html' %}

{% block content %}
    <div class="container-fluid">
        <table class="table table-striped table-hover table-sm small">
            <thead class="thead-unesp">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Turma</th>
                    <th scope="col">Disciplina</th>
                    <th scope="col">Curso</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Oferecimento</th>
                </tr>
            </thead>
            {% for turma in turmas %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ turma.disciplina.codigo }}{{ turma.turma }}</td>
                    <td>{{ turma.disciplina.nome }}</td>
                    <td>{{ turma.curso }}</td>
                    <td>{{ turma.get_tipo_display }}</td>
                    <td>{{ turma.calendario }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}